apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mysql/mysql_data
  claimRef:
    name: mysql-pvc
    namespace: default
