apiVersion: v1
kind: Service
metadata:
  name: my-mysql
  namespace: default
spec:
  selector:
    app: my-mysql
  type: NodePort
  ports:
  - name: my-mysql
    protocol: TCP
    port: 3306
    targetPort: 3306