apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mysql
  namespace: default
  labels:
    app: my-mysql
spec:
  selector:
    matchLabels:
      app: my-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      containers:
      - name: my-mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort:  3306
          name: my-mysql
