apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: default
spec:
  selector:
    app: my-nginx
  type: LoadBalancer
  ports:
  - name: my-nginx
    protocol: TCP
    port: 80
    targetPort: 80