apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-app
  name: prometheus-app-svc
  namespace: default
spec:
  selector:
    app: prometheus-app
  type: NodePort
  ports:
  - nodePort: 30990
    port: 9090
    protocol: TCP
    targetPort: 9090
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.