apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app
  namespace: default
  labels:
    app: prometheus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      containers:
      - name: prometheus-app
        image: prom/prometheus
        args:
        - "--config.file=/etc/prometheus/prometheus-config.yaml"
        ports:
        - containerPort:  9090
          name: prometheus-app
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: storage-volume
          mountPath: /prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-kubernetes
        - name: storage-volume
          emptyDir: {}
